# config/local.yaml

env: "local" # local, dev, prod
storage_path: "./storage/banner.db" # файл, в котором будет храниться наша БД
http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
